Fix broken Github windows build, due to different rules for `[[deprecated]]`.
  - ".\iamf/cli/wav_writer.h(74): error C3827: standard attribute [[deprecated]] may have either no arguments or one string literal describing the reason"

PiperOrigin-RevId: 715061479